### ISSUE TITLE
when I click the report button on post I will get an error

### ISSUE THREAD

**Issue by 21Gxme** [SmileyFaceZ/KU-Hub#102]
<img width="1470" alt="image" src="https://github.com/SmileyFaceZ/KU-Hub/assets/113856957/55550aae-61f2-4fa2-b73c-1a7d4a6161b0">

**Comment by woraamy** [comment]
You can use the report now, the problem occurred because the Summary-Hub's posts are filtered out as PostDownload objects, so it does not link to the PostReport object.
