### ISSUE TITLE
I can't use see comments

### ISSUE THREAD

**Issue by Peanutt47** [SmileyFaceZ/KU-Hub#103]
![image](https://github.com/SmileyFaceZ/KU-Hub/assets/85238329/4a56b1d7-da30-4ad8-88d5-6c61de53106b)
when i can't click ''See comments" button on "https://ku-hub.onrender.com/kuhub/post/4/'

**Comment by woraamy** [comment]
You can use it now, the problem occurred because the program filters out PostDownloads instead of normal Posts, so it does not connect to the comments
