### ISSUE TITLE
i can't use "Search" button

### ISSUE THREAD

**Issue by Peanutt47** [SmileyFaceZ/KU-Hub#106]
![image](https://github.com/SmileyFaceZ/KU-Hub/assets/85238329/53a6fb9d-8435-4a52-9584-7ab9ee27257d)
![image](https://github.com/SmileyFaceZ/KU-Hub/assets/85238329/a809403a-b956-4784-886b-3024c41807f0)
i can't use "Search" when i use Order by Download: = Most Download and least Download without fill another filter

**Comment by SmileyFaceZ** [comment]
Thanks you for your observation.
I will looking into it.

**Comment by SmileyFaceZ** [comment]
Right now our application doesn't have a download feature. 
The file data is connect with Firebase and it pretty hard to get it when download it got a .html file instead.
