### ISSUE TITLE
can't join the group eventhough I put the correct password

### ISSUE THREAD

**Issue by 21Gxme** [SmileyFaceZ/KU-Hub#107]
<img width="1470" alt="image" src="https://github.com/SmileyFaceZ/KU-Hub/assets/113856957/5f5177ba-0c62-457d-b4c0-4f99e08810eb">

**Comment by SmileyFaceZ** [comment]
What is your group is to create?
I think you already in the group you can see that in the left side bar.

**Comment by 21Gxme** [comment]
I create MAMA group password 1234 and give password to my friend but my friend can't join the group even though put the correct password.

**Comment by tnnpp** [comment]
I have already checked and it can join normally. Can you try again.
