### ISSUE TITLE
can't change to other subject when I want to post.

### ISSUE THREAD

**Issue by 21Gxme** [SmileyFaceZ/KU-Hub#110]
<img width="605" alt="image" src="https://github.com/SmileyFaceZ/KU-Hub/assets/113856957/3b01cf21-f45c-4474-a4b5-9e9e86ee7fb3">

**Comment by SmileyFaceZ** [comment]
Thankyou for your attention. I will fix it.

**Comment by SmileyFaceZ** [comment]
The subject tag is match when user select. Feel free to create post.
