### ISSUE TITLE
Can't submit report

### ISSUE THREAD

**Issue by Peanutt47** [SmileyFaceZ/KU-Hub#111]
![image](https://github.com/SmileyFaceZ/KU-Hub/assets/85238329/9a799307-7eaa-4c14-b838-8d23024b4981)
I can't submit a report. I use the report button on the review-hub page.

**Comment by woraamy** [comment]
You actually already submitted the report after pressing the "Submit Report" button, but the app didn't show the success message when the Report object was created. I fixed it to show the success message now.
