### ISSUE TITLE
DEBUG = True so I can get into admin page and see all path in urls when type nonexisted URL

### ISSUE THREAD

**Issue by Sosokker** [SmileyFaceZ/KU-Hub#113]
Admin Page
![image](https://github.com/SmileyFaceZ/KU-Hub/assets/22256420/c72c9628-db28-446d-a209-8b31b8c4fe23)

Url Route
![image](https://github.com/SmileyFaceZ/KU-Hub/assets/22256420/9ec07665-2df7-4d15-9c50-fcbcc0cf9565)

**Comment by SmileyFaceZ** [comment]
Duplicated like issues 98.
