### ISSUE TITLE
Include Potential Data in directory data in Repository 

### ISSUE THREAD

**Issue by Sosokker** [SmileyFaceZ/KU-Hub#114]
[https://github.com/SmileyFaceZ/KU-Hub/tree/main/data](https://github.com/SmileyFaceZ/KU-Hub/tree/main/data) Include many data such as
***All Data in database*** -> [https://github.com/SmileyFaceZ/KU-Hub/blob/main/data/all-data.json](https://github.com/SmileyFaceZ/KU-Hub/blob/main/data/all-data.json)
1. Post data 
2. Group Data
3. User Data Files
4. [Has superuser detail](https://github.com/SmileyFaceZ/KU-Hub/blob/main/data/users-v2-utf8-no-bom.json)
5. Google Platform Info

Please delete and keep those information secret.

**Comment by SmileyFaceZ** [comment]
Thankyou for your attention. I delete it already
