### ISSUE TITLE
can't view the file in summary hub

### ISSUE THREAD

**Issue by 21Gxme** [SmileyFaceZ/KU-Hub#123]
<img width="1470" alt="image" src="https://github.com/SmileyFaceZ/KU-Hub/assets/113856957/f670d5c1-e6a2-4131-b4c9-79cbfd88645e">

**Comment by SmileyFaceZ** [comment]
Thank you for conducting the test. We are now connected to Firebase. 
However, the file cannot be opened because it is saved in a local project. Once the file is deleted, it cannot be reopened.
