### ISSUE TITLE
can't access summary-hub

### ISSUE THREAD

**Issue by 21Gxme** [SmileyFaceZ/KU-Hub#126]
<img width="1470" alt="image" src="https://github.com/SmileyFaceZ/KU-Hub/assets/113856957/df8d0585-bd1b-4dfd-a4f7-208abd839420">

**Comment by SmileyFaceZ** [comment]
Since We are processing to store file in **Firebase**. In the HTML it not done yet
Thank you for your observation.

**Comment by jbrucker** [comment]
This is a defect.  Actually it is **TWO DEFECTS**.

1. Tantikorn clearly got an error page while using your app.  Respondihg "its not done yet" does not excuse the error.
2. Tantikorn got a Traceback, which looks like you deployed your app with DEBUG=True.

Find the code that caused the problem and add try - except.
In the "catch" block using LOGGING to record the error.

All projects must use logging for anything likely to fail, which includes
external services like Firebase.
